# Generated by Django 2.2.2 on 2019-06-08 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet', models.CharField(max_length=50)),
                ('date', models.DateTimeField(verbose_name='date')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
    ]
